server:
  port: 8091

spring:
  application:
    name: audit-service

  datasource:
    password: banking_pass
    url: jdbc:postgresql://localhost:5432/banking_db
    username: banking
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  rabbitmq:
    host: localhost
    password: banking_pass
    username: banking
