-- ============================================================
-- V1: Baseline schema for the 5ive banking platform
-- Target: PostgreSQL 16 (banking_db), owner: banking
-- Generated from the current JPA entities (core-data-lib).
-- All tables in banking_db are owned/created by core-app-service.
-- ============================================================

-- ------------------------------------------------------------
-- Identity / audit base columns (BaseModel, AuditModel)
-- ------------------------------------------------------------

-- ------------------------------------------------------------
-- Users, roles, permissions
-- ------------------------------------------------------------

CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(255),
    uid                 VARCHAR(255),
    email               VARCHAR(255),
    password            VARCHAR(255),
    transaction_pin     VARCHAR(255),
    pin_set_at          TIMESTAMP(6),
    pin_attempts        INTEGER,
    last_logout_date    TIMESTAMP(6),
    avatar_url          VARCHAR(500),
    deleted             BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP(6),
    created_by          VARCHAR(255),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(255),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_uid UNIQUE (uid),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name       VARCHAR(255),
    description     VARCHAR(255),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6),
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(255),
    CONSTRAINT uq_roles_role_name UNIQUE (role_name)
);

CREATE TABLE permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name VARCHAR(255),
    description     VARCHAR(255),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6),
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(255),
    CONSTRAINT uq_permissions_permission_name UNIQUE (permission_name)
);

CREATE TABLE users_roles (
    user_id     BIGINT NOT NULL,
    roles_id    BIGINT NOT NULL,
    PRIMARY KEY (user_id, roles_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_users_roles_role FOREIGN KEY (roles_id) REFERENCES roles (id)
);

CREATE TABLE roles_permissions (
    role_id         BIGINT NOT NULL,
    permissions_id  BIGINT NOT NULL,
    PRIMARY KEY (role_id, permissions_id),
    CONSTRAINT fk_roles_permissions_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_roles_permissions_perm FOREIGN KEY (permissions_id) REFERENCES permissions (id)
);

CREATE TABLE users_permissions (
    user_id         BIGINT NOT NULL,
    permissions_id  BIGINT NOT NULL,
    PRIMARY KEY (user_id, permissions_id),
    CONSTRAINT fk_users_permissions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_users_permissions_perm FOREIGN KEY (permissions_id) REFERENCES permissions (id)
);

-- ------------------------------------------------------------
-- User OTP
-- ------------------------------------------------------------

CREATE TABLE user_otps (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uid        VARCHAR(255) NOT NULL,
    otp_code        VARCHAR(6) NOT NULL,
    otp_type        VARCHAR(255) NOT NULL,
    expires_at      TIMESTAMP(6) NOT NULL,
    verified_at     TIMESTAMP(6),
    attempt_count   INTEGER NOT NULL DEFAULT 0,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6),
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(255),
    CONSTRAINT ck_user_otps_otp_type CHECK (otp_type IN
        ('FORGOT_PASSWORD', 'EMAIL_VERIFICATION', 'PHONE_VERIFICATION',
         'TRANSACTION_CONFIRMATION', 'ACCOUNT_ACTIVATION'))
);

-- ------------------------------------------------------------
-- User profile & KYC
-- ------------------------------------------------------------

CREATE TABLE user_profile (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    other_names     VARCHAR(255),
    middle_name     VARCHAR(255),
    date_of_birth   DATE,
    gender          VARCHAR(255),
    phone_number    VARCHAR(20),
    address         VARCHAR(255),
    city            VARCHAR(255),
    country         VARCHAR(255),
    state           VARCHAR(255),
    zip             VARCHAR(255),
    longitude       VARCHAR(255),
    latitude        VARCHAR(255),
    location_type   VARCHAR(255),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6),
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(255),
    CONSTRAINT uq_user_profile_user_id UNIQUE (user_id),
    CONSTRAINT ck_user_profile_gender CHECK (gender IN ('MALE', 'FEMALE')),
    CONSTRAINT ck_user_profile_location_type CHECK (location_type IN
        ('HOME', 'WORK', 'BUSINESS', 'OTHER'))
);

CREATE TABLE user_kyc (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id         BIGINT,
    bvn_no                  VARCHAR(255),
    bvn_verification_status VARCHAR(255),
    nin_no                  VARCHAR(255),
    nin_verification_status VARCHAR(255),
    tier                    VARCHAR(255),
    deleted                 BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP(6),
    created_by              VARCHAR(255),
    updated_at              TIMESTAMP(6),
    updated_by              VARCHAR(255),
    CONSTRAINT uq_user_kyc_user_profile_id UNIQUE (user_profile_id),
    CONSTRAINT fk_user_kyc_profile FOREIGN KEY (user_profile_id) REFERENCES user_profile (id),
    CONSTRAINT ck_user_kyc_bvn_status CHECK (bvn_verification_status IN ('UNVERIFIED', 'VERIFIED', 'PENDING')),
    CONSTRAINT ck_user_kyc_nin_status CHECK (nin_verification_status IN ('UNVERIFIED', 'VERIFIED', 'PENDING')),
    CONSTRAINT ck_user_kyc_tier CHECK (tier IN ('TIER_1', 'TIER_2', 'TIER_3'))
);

CREATE TABLE customer_profile (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    phone_number    VARCHAR(255),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6),
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(255)
);

-- ------------------------------------------------------------
-- Accounts
-- ------------------------------------------------------------

CREATE TABLE accounts (
    id              UUID PRIMARY KEY,
    account_number  VARCHAR(10) NOT NULL,
    account_name    VARCHAR(255) NOT NULL,
    account_type    VARCHAR(255) NOT NULL,
    balance         NUMERIC(19, 2) NOT NULL DEFAULT 0,
    currency        VARCHAR(3) NOT NULL DEFAULT 'NGN',
    status          VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    user_id         BIGINT NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_accounts_account_number UNIQUE (account_number),
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_accounts_user_id ON accounts (user_id);

-- ------------------------------------------------------------
-- Transfers
-- ------------------------------------------------------------

CREATE TABLE transfers (
    id                          UUID PRIMARY KEY,
    reference                   VARCHAR(255) NOT NULL,
    source_account_number       VARCHAR(10) NOT NULL,
    destination_account_number  VARCHAR(10) NOT NULL,
    amount                      NUMERIC(19, 2) NOT NULL,
    description                 TEXT,
    idempotency_key             VARCHAR(64),
    status                      VARCHAR(255) NOT NULL DEFAULT 'COMPLETED',
    created_at                  TIMESTAMP(6) NOT NULL,
    updated_at                  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_transfers_reference UNIQUE (reference)
);

CREATE INDEX idx_transfers_source_account ON transfers (source_account_number);
CREATE INDEX idx_transfers_dest_account ON transfers (destination_account_number);

-- ------------------------------------------------------------
-- Bill payments
-- ------------------------------------------------------------

CREATE TABLE bill_payments (
    id                      UUID PRIMARY KEY,
    reference               VARCHAR(255) NOT NULL,
    source_account_number   VARCHAR(10) NOT NULL,
    provider                VARCHAR(255) NOT NULL,
    customer_reference      VARCHAR(255) NOT NULL,
    amount                  NUMERIC(19, 2),
    description             TEXT,
    status                  VARCHAR(255) NOT NULL,
    created_at              TIMESTAMP(6),
    updated_at              TIMESTAMP(6),
    CONSTRAINT uq_bill_payments_reference UNIQUE (reference)
);

CREATE INDEX idx_bill_payments_source_account ON bill_payments (source_account_number);

-- ------------------------------------------------------------
-- Ledger / account transactions
-- ------------------------------------------------------------

CREATE TABLE account_transactions (
    id                          UUID PRIMARY KEY,
    reference                   VARCHAR(255) NOT NULL,
    account_number              VARCHAR(10) NOT NULL,
    counterparty_account_number VARCHAR(10),
    amount                      NUMERIC(19, 2) NOT NULL,
    type                        VARCHAR(255) NOT NULL,
    description                 TEXT,
    status                      VARCHAR(255) NOT NULL DEFAULT 'COMPLETED',
    created_at                  TIMESTAMP(6) NOT NULL,
    updated_at                  TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_account_transactions_account_created
    ON account_transactions (account_number, created_at DESC);

-- ------------------------------------------------------------
-- Beneficiaries
-- ------------------------------------------------------------

CREATE TABLE beneficiaries (
    id              UUID PRIMARY KEY,
    alias           VARCHAR(255) NOT NULL,
    account_number  VARCHAR(10) NOT NULL,
    bank_name       VARCHAR(255),
    description     TEXT,
    user_id         BIGINT NOT NULL,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT fk_beneficiaries_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_beneficiaries_user_id ON beneficiaries (user_id);

-- ------------------------------------------------------------
-- Cards
-- ------------------------------------------------------------

CREATE TABLE cards (
    id              UUID PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    account_number  VARCHAR(10) NOT NULL,
    card_number     VARCHAR(16) NOT NULL,
    card_type       VARCHAR(20) NOT NULL,
    expiry_date     DATE NOT NULL,
    cvv             VARCHAR(3) NOT NULL,
    pin_hash        VARCHAR(255) NOT NULL,
    status          VARCHAR(255) NOT NULL,
    daily_limit     NUMERIC(19, 2),
    monthly_limit   NUMERIC(19, 2),
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT uq_cards_card_number UNIQUE (card_number),
    CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_cards_user_id ON cards (user_id);
CREATE INDEX idx_cards_account_number ON cards (account_number);

-- ------------------------------------------------------------
-- Notifications
-- ------------------------------------------------------------

CREATE TABLE user_notifications (
    id          UUID PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    type        VARCHAR(20) NOT NULL,
    title       VARCHAR(255) NOT NULL,
    body        TEXT,
    is_read     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_notifications_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_user_notifications_user_created
    ON user_notifications (user_id, created_at DESC);

CREATE TABLE user_notification_preferences (
    id                   UUID PRIMARY KEY,
    user_id              BIGINT NOT NULL,
    security_alerts      BOOLEAN NOT NULL DEFAULT TRUE,
    transaction_alerts   BOOLEAN NOT NULL DEFAULT TRUE,
    promotional_updates  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_user_notification_prefs_user UNIQUE (user_id),
    CONSTRAINT fk_user_notification_prefs_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ------------------------------------------------------------
-- Outbox (event-driven publishing)
-- ------------------------------------------------------------

CREATE TABLE outbox_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR(255) NOT NULL,
    aggregate_id    VARCHAR(255) NOT NULL,
    event_type      VARCHAR(255) NOT NULL,
    payload         TEXT,
    status          VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    retry_count     INTEGER NOT NULL DEFAULT 0,
    valid_until     TIMESTAMP(6),
    published_at    TIMESTAMP(6),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6),
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(255),
    CONSTRAINT ck_outbox_events_status CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

CREATE INDEX idx_outbox_status_validuntil ON outbox_events (status, valid_until);

-- ------------------------------------------------------------
-- Admin: approvals, limits, audit logs
-- ------------------------------------------------------------

CREATE TABLE admin_approvals (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type     VARCHAR(255) NOT NULL,
    action_payload  TEXT,
    requested_by    BIGINT NOT NULL,
    status          VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    reviewed_by     BIGINT,
    review_note     VARCHAR(255),
    reason          VARCHAR(255),
    risk_level      VARCHAR(255) NOT NULL,
    correlation_id  VARCHAR(255),
    expires_at      TIMESTAMP(6),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6),
    created_by      VARCHAR(255),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(255),
    CONSTRAINT ck_admin_approvals_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED'))
);

CREATE INDEX idx_approval_status ON admin_approvals (status);
CREATE INDEX idx_approval_action_type ON admin_approvals (action_type);

CREATE TABLE account_type_limits (
    id                    UUID PRIMARY KEY,
    account_type          VARCHAR(30) NOT NULL,
    daily_transfer_limit  NUMERIC(19, 2) NOT NULL,
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_account_type_limits_account_type UNIQUE (account_type)
);

CREATE TABLE audit_logs (
    id           UUID PRIMARY KEY,
    user_id      BIGINT,
    action       VARCHAR(40) NOT NULL,
    entity_type  VARCHAR(40),
    entity_id    VARCHAR(60),
    detail       TEXT,
    created_at   TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);

-- ------------------------------------------------------------
-- Audit events (written by audit-service, same database)
-- ------------------------------------------------------------

CREATE TABLE audit_events (
    id               UUID PRIMARY KEY,
    event_type       VARCHAR(60) NOT NULL,
    action           VARCHAR(120),
    actor_id         VARCHAR(60),
    actor_type       VARCHAR(20),
    actor_name       VARCHAR(100),
    actor_email      VARCHAR(150),
    target_type      VARCHAR(40),
    target_id        VARCHAR(80),
    target_name      VARCHAR(100),
    ip_address       VARCHAR(45),
    user_agent       VARCHAR(255),
    device_id        VARCHAR(80),
    service_name     VARCHAR(60),
    request_id       VARCHAR(80),
    correlation_id   VARCHAR(80),
    status           VARCHAR(20),
    risk_level       VARCHAR(20),
    reason           VARCHAR(500),
    before_state     TEXT,
    after_state      TEXT,
    metadata         TEXT,
    amount           NUMERIC(19, 4),
    currency         VARCHAR(3),
    occurred_at      TIMESTAMP(6) NOT NULL,
    created_at       TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_audit_event_type ON audit_events (event_type);
CREATE INDEX idx_audit_actor ON audit_events (actor_id);
CREATE INDEX idx_audit_target ON audit_events (target_type, target_id);
CREATE INDEX idx_audit_risk_level ON audit_events (risk_level);
CREATE INDEX idx_audit_occurred_at ON audit_events (occurred_at);

-- ------------------------------------------------------------
-- Email deliveries (written by email-service, same database)
-- ------------------------------------------------------------

CREATE TABLE email_deliveries (
    id                 UUID PRIMARY KEY,
    notification_type  VARCHAR(255) NOT NULL,
    recipient          VARCHAR(255) NOT NULL,
    subject            VARCHAR(255),
    body               TEXT,
    status             VARCHAR(255) NOT NULL,
    retry_count        INTEGER NOT NULL DEFAULT 0,
    failure_reason     TEXT,
    sent_at            TIMESTAMP(6),
    related_event_id   VARCHAR(255),
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6)
);

CREATE INDEX idx_email_deliveries_recipient ON email_deliveries (recipient);
CREATE INDEX idx_email_deliveries_status ON email_deliveries (status);