spring.banner.location=classpath:banner.txt

spring.mail.host=127.0.0.1
spring.mail.port=1025

spring.rabbitmq.host=localhost
spring.rabbitmq.username=banking
spring.rabbitmq.password=banking_pass

server.port=8090