spring.banner.location=classpath:banner.txt

app.bank.name=Aurum Bank
app.bank.support-email=support@aurum.bank
app.bank.website=aurum.bank

spring.mail.host=127.0.0.1
spring.mail.port=1025

spring.rabbitmq.host=localhost
spring.rabbitmq.username=banking
spring.rabbitmq.password=banking_pass

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=banking
spring.datasource.password=banking_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8090